In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,11)

In [ ]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr[2:7])



[3 4 5 6 7]


In [ ]:
print(arr[2:7:2])

[3 5 7]


In [ ]:
print(arr[-3])

8


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d[1,2]) #2nd row 3rd digit
print(arr_2d[1]) # complete second row
print(arr_2d[:,2]) # all rows 3rd columne


6
[4 5 6]
[3 6]


In [ ]:
arr_2d_unsorted = np.array([[1,3,2],[4,1,7]])
print(arr_2d_unsorted)
arr_2d_sorted = np.sort(arr_2d_unsorted,1)
print(arr_2d_sorted)

[[1 3 2]
 [4 1 7]]
[[1 2 3]
 [1 4 7]]


In [ ]:
numbers = np.arange(1,13)
even_numbers = numbers[numbers %2 == 0]
print(even_numbers)


[ 2  4  6  8 10 12]


In [ ]:
mask = numbers > 5
print(mask)

print(numbers[mask])

[False False False False False  True  True  True  True  True  True  True]
[ 6  7  8  9 10 11 12]


In [ ]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [ ]:
where_result = np.where(numbers > 5)
print(where_result)
print(numbers[where_result])

(array([ 5,  6,  7,  8,  9, 10, 11]),)
[ 6  7  8  9 10 11 12]


In [ ]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20 22 24]


In [ ]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([10,20,30])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)


[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [ ]:
new_col = np.array([[100,200],[300,400]])
with_new_col = np.column_stack((original,new_col))
print(with_new_col)

[[  1   2   3 100 200]
 [  4   5   6 300 400]]
