In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)

[1 2 3 4 5 6]


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
py_list = [1,2,3]
print("python list multiplication", py_list * 3)

python list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1,2,3])
print("numpy array multiplication", np_array * 3)


numpy array multiplication [3 6 9]


In [ ]:
import time

In [ ]:
start = time.time()
pylist = [i*2 for i in range(100000)]
end = time.time()
print("time taken by python list", end-start)

time taken by python list 0.0070455074310302734


In [ ]:
start = time.time()
np_array = np.arange(100000) *2
end = time.time()
print("time taken by python list", end-start)

time taken by python list 0.0031557083129882812


In [ ]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full = np.full((3,3), 5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
random = np.random.random((3,3))
print(random)


[[0.48999997 0.69682832 0.46761475]
 [0.53865123 0.11691798 0.68140664]
 [0.83381035 0.89843674 0.6505814 ]]


In [ ]:
sequence = np.arange(5,15,3)
print(sequence)

[ 5  8 11 14]


In [ ]:
vector = np.array([1,2,3,4,5])
print(vector)
#

[1 2 3 4 5]


In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print("Shape",tensor.shape)
print("Size",tensor.size)
print("Dimension",tensor.ndim)
print("Data Type",tensor.dtype)

Shape (2, 2, 2)
Size 8
Dimension 3
Data Type int64


In [ ]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
reshaped = arr.reshape(4,3)
print(reshaped)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
flattened = reshaped.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
