In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])


In [ ]:
print(sales_data)

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]


In [ ]:
print(sales_data[:3])

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
print(np.sum(sales_data[:,1:],1,))


[800000 610000 990000 900000 780000]


In [ ]:
print(np.cumsum(sales_data[:,1:],axis=1))

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
print( np.dot(vector1, vector2))
print(np.add(vector1, vector2))
print(np.subtract(vector1, vector2))
print(np.multiply(vector1, vector2))

#

32
[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [ ]:
restaurant_types = np.array(['Paradise Biryani', 'Beijing Bites', 'Pizza Hub', 'Burger Point', 'Chai Point'])
print(restaurant_types)
vectorized_upper = np.vectorize(str.upper)
print(vectorized_upper(restaurant_types))

['Paradise Biryani' 'Beijing Bites' 'Pizza Hub' 'Burger Point'
 'Chai Point']
['PARADISE BIRYANI' 'BEIJING BITES' 'PIZZA HUB' 'BURGER POINT'
 'CHAI POINT']


In [ ]:
monthly_avg = np.sum(sales_data[:,1:], axis=0) / 4
print(monthly_avg)

[202500. 236250. 271250. 310000.]
